server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: hotel-reservation
          uri: http://localhost:8082
          predicates:
            - Path=/hotels/**, 
        - id: hotel-management
          uri: http://localhost:8083
          predicates:
            - Path=/hotelManagers/**, 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: hotel-reservation
          uri: http://hotelReservation:8080
          predicates:
            - Path=/hotels/**, 
        - id: hotel-management
          uri: http://hotelManagement:8080
          predicates:
            - Path=/hotelManagers/**, 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
