---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel-reservation
  labels:
    app: hotel-reservation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotel-reservation
  template:
    metadata:
      labels:
        app: hotel-reservation
    spec:
      containers:
        - name: hotel-reservation
          image: username/hotel-reservation:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel-management
  labels:
    app: hotel-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hotel-management
  template:
    metadata:
      labels:
        app: hotel-management
    spec:
      containers:
        - name: hotel-management
          image: username/hotel-management:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: hotel-reservation
  labels:
    app: hotel-reservation
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: hotel-reservation


---


apiVersion: v1
kind: Service
metadata:
  name: hotel-management
  labels:
    app: hotel-management
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: hotel-management

